default:
  image: $CI_REGISTRY_IMAGE:latest
#  tags:
#    - my-tag

before_script:
  - export GRADLE_USER_HOME=cache/.gradle
  - echo $KEYSTORE | base64 -d -i > /tmp/my-release-key.keystore
  - echo $SA_JSON_KEY | base64 -d -i > key_firebase.json
  - echo $GOOGLE_SERVICES_JSON | base64 -d -i > app/google-services.json

cache:
  key:
    files:
      - gradle/wrapper/gradle-wrapper.properties
  paths:
    - $PWD/cache/.gradle/

stages:
  - build_base_image
  - tests
  - deploy_staging
  - deploy_prod

build_base_image:
  rules:
    - if: $CI_COMMIT_REF_NAME == "main"
      changes:
        - Dockerfile
  image: docker:dind
  stage: build_base_image
  services:
    - name: docker:dind
      entrypoint: ["env", "-u", "DOCKER_HOST"]
      command: ["dockerd-entrypoint.sh"]
  variables:
      DOCKER_HOST: tcp://docker:2375/
      DOCKER_DRIVER: overlay2
      DOCKER_TLS_CERTDIR: ""
  before_script:
    - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN $CI_REGISTRY_IMAGE
  script:
    - docker pull $CI_REGISTRY_IMAGE:latest || true
    - docker build --cache-from $CI_REGISTRY_IMAGE:latest --tag $CI_REGISTRY_IMAGE:latest .
    - docker push $CI_REGISTRY_IMAGE:latest

lints:
  rules:
    - if: $CI_PIPELINE_SOURCE == "merge_request_event" && $CI_MERGE_REQUEST_TARGET_BRANCH_NAME == "main"
    - if: $CI_COMMIT_REF_NAME == "main"
  stage: tests
  script:
    - bundle exec fastlane lint

unit_test:
  rules:
    - if: $CI_PIPELINE_SOURCE == "merge_request_event" && $CI_MERGE_REQUEST_TARGET_BRANCH_NAME == "main"
    - if: $CI_COMMIT_REF_NAME == "main"
  stage: tests
  script:
    - bundle exec fastlane unit_test

staging_firebase:
  rules:
    - if: $CI_PIPELINE_SOURCE == "merge_request_event" && $CI_MERGE_REQUEST_TARGET_BRANCH_NAME == "main"
      when: manual
    - if: $CI_COMMIT_REF_NAME == "main"
  stage: deploy_staging
  script:
    - bundle exec fastlane firebase_distribution
  environment:
    name: staging

prod_firebase:
  rules:
    - if: $CI_COMMIT_REF_NAME == "main"
  stage: deploy_prod
  script:
    - bundle exec fastlane firebase_distribution
  artifacts:
    paths:
      - app/build/outputs/bundle/release/app-release.aab
    expire_in: 1 day
  environment:
    name: prod

google_play:
  rules:
    - if: $CI_COMMIT_REF_NAME == "main"
      when: manual
  stage: deploy_prod
  script:
    - echo $SA_JSON_GP_KEY | base64 -d -i > key_gp.json
    - bundle exec fastlane google_beta
  dependencies:
    - prod_firebase
  environment:
    name: prod-gp
  when: manual
